// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Resend.OpenApiClient.Webhooks.Item.SigningSecret.Rotate;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Resend.OpenApiClient.Webhooks.Item.SigningSecret
{
    /// <summary>
    /// Builds and executes requests for operations under \webhooks\{webhookId}\signing-secret
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SigningSecretRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The rotate property</summary>
        public global::Soenneker.Resend.OpenApiClient.Webhooks.Item.SigningSecret.Rotate.RotateRequestBuilder Rotate
        {
            get => new global::Soenneker.Resend.OpenApiClient.Webhooks.Item.SigningSecret.Rotate.RotateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Webhooks.Item.SigningSecret.SigningSecretRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SigningSecretRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks/{webhookId}/signing-secret", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Webhooks.Item.SigningSecret.SigningSecretRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SigningSecretRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks/{webhookId}/signing-secret", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
