// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The API key can have full access to Resend’s API or be only restricted to send emails. * full_access - Can create, delete, get, and update any resource. * sending_access - Can only send emails.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateApiKeyRequest_permission
    {
        [EnumMember(Value = "full_access")]
        #pragma warning disable CS1591
        Full_access,
        #pragma warning restore CS1591
        [EnumMember(Value = "sending_access")]
        #pragma warning disable CS1591
        Sending_access,
        #pragma warning restore CS1591
    }
}
