// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>
    /// Configure the domain capabilities for sending and receiving emails. At least one capability must be enabled.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DomainCapabilities : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Enable or disable receiving emails to this domain.</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.DomainCapabilities_receiving? Receiving { get; set; }
        /// <summary>Enable or disable sending emails from this domain.</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.DomainCapabilities_sending? Sending { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.DomainCapabilities"/> and sets the default values.
        /// </summary>
        public DomainCapabilities()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.DomainCapabilities"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.DomainCapabilities CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.DomainCapabilities();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "receiving", n => { Receiving = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainCapabilities_receiving>(); } },
                { "sending", n => { Sending = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainCapabilities_sending>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainCapabilities_receiving>("receiving", Receiving);
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainCapabilities_sending>("sending", Sending);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
