// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListReceivedEmailsResponse_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Array of attachments for this email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Resend.OpenApiClient.Models.ListReceivedEmailsResponse_data_attachments>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Resend.OpenApiClient.Models.ListReceivedEmailsResponse_data_attachments> Attachments { get; set; }
#endif
        /// <summary>The BCC recipients.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Bcc { get; set; }
#nullable restore
#else
        public List<string> Bcc { get; set; }
#endif
        /// <summary>The CC recipients.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Cc { get; set; }
#nullable restore
#else
        public List<string> Cc { get; set; }
#endif
        /// <summary>Timestamp when the email was received.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The sender email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>The ID of the received email.</summary>
        public Guid? Id { get; set; }
        /// <summary>The unique message ID from the email headers.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageId { get; set; }
#nullable restore
#else
        public string MessageId { get; set; }
#endif
        /// <summary>The reply-to addresses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? ReplyTo { get; set; }
#nullable restore
#else
        public List<string> ReplyTo { get; set; }
#endif
        /// <summary>The email subject.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The recipient email addresses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? To { get; set; }
#nullable restore
#else
        public List<string> To { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.ListReceivedEmailsResponse_data"/> and sets the default values.
        /// </summary>
        public ListReceivedEmailsResponse_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.ListReceivedEmailsResponse_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.ListReceivedEmailsResponse_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.ListReceivedEmailsResponse_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.Resend.OpenApiClient.Models.ListReceivedEmailsResponse_data_attachments>(global::Soenneker.Resend.OpenApiClient.Models.ListReceivedEmailsResponse_data_attachments.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bcc", n => { Bcc = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "cc", n => { Cc = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "id", n => { Id = n.GetGuidValue(); } },
                { "message_id", n => { MessageId = n.GetStringValue(); } },
                { "reply_to", n => { ReplyTo = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "to", n => { To = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Resend.OpenApiClient.Models.ListReceivedEmailsResponse_data_attachments>("attachments", Attachments);
            writer.WriteCollectionOfPrimitiveValues<string>("bcc", Bcc);
            writer.WriteCollectionOfPrimitiveValues<string>("cc", Cc);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("from", From);
            writer.WriteGuidValue("id", Id);
            writer.WriteStringValue("message_id", MessageId);
            writer.WriteCollectionOfPrimitiveValues<string>("reply_to", ReplyTo);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("to", To);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
