// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SendEmailRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The attachments property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Resend.OpenApiClient.Models.Attachment>? Attachments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Resend.OpenApiClient.Models.Attachment> Attachments { get; set; }
#endif
        /// <summary>Bcc recipient email address. For multiple addresses, send as an array of strings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Bcc { get; set; }
#nullable restore
#else
        public string Bcc { get; set; }
#endif
        /// <summary>Cc recipient email address. For multiple addresses, send as an array of strings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cc { get; set; }
#nullable restore
#else
        public string Cc { get; set; }
#endif
        /// <summary>Sender email address. To include a friendly name, use the format &quot;Your Name &lt;sender@domain.com&gt;&quot;.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>Custom headers to add to the email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.SendEmailRequest_headers? Headers { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.SendEmailRequest_headers Headers { get; set; }
#endif
        /// <summary>The HTML version of the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Html { get; set; }
#nullable restore
#else
        public string Html { get; set; }
#endif
        /// <summary>Reply-to email address. For multiple addresses, send as an array of strings.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReplyTo { get; set; }
#nullable restore
#else
        public string ReplyTo { get; set; }
#endif
        /// <summary>Schedule email to be sent later. The date should be in ISO 8601 format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ScheduledAt { get; set; }
#nullable restore
#else
        public string ScheduledAt { get; set; }
#endif
        /// <summary>Email subject.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Resend.OpenApiClient.Models.Tag>? Tags { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Resend.OpenApiClient.Models.Tag> Tags { get; set; }
#endif
        /// <summary>The plain text version of the message.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Text { get; set; }
#nullable restore
#else
        public string Text { get; set; }
#endif
        /// <summary>The to property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? To { get; set; }
#nullable restore
#else
        public List<string> To { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.SendEmailRequest"/> and sets the default values.
        /// </summary>
        public SendEmailRequest()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.SendEmailRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.SendEmailRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.SendEmailRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "attachments", n => { Attachments = n.GetCollectionOfObjectValues<global::Soenneker.Resend.OpenApiClient.Models.Attachment>(global::Soenneker.Resend.OpenApiClient.Models.Attachment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bcc", n => { Bcc = n.GetStringValue(); } },
                { "cc", n => { Cc = n.GetStringValue(); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "headers", n => { Headers = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.SendEmailRequest_headers>(global::Soenneker.Resend.OpenApiClient.Models.SendEmailRequest_headers.CreateFromDiscriminatorValue); } },
                { "html", n => { Html = n.GetStringValue(); } },
                { "reply_to", n => { ReplyTo = n.GetStringValue(); } },
                { "scheduled_at", n => { ScheduledAt = n.GetStringValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfObjectValues<global::Soenneker.Resend.OpenApiClient.Models.Tag>(global::Soenneker.Resend.OpenApiClient.Models.Tag.CreateFromDiscriminatorValue)?.AsList(); } },
                { "text", n => { Text = n.GetStringValue(); } },
                { "to", n => { To = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Resend.OpenApiClient.Models.Attachment>("attachments", Attachments);
            writer.WriteStringValue("bcc", Bcc);
            writer.WriteStringValue("cc", Cc);
            writer.WriteStringValue("from", From);
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.SendEmailRequest_headers>("headers", Headers);
            writer.WriteStringValue("html", Html);
            writer.WriteStringValue("reply_to", ReplyTo);
            writer.WriteStringValue("scheduled_at", ScheduledAt);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Resend.OpenApiClient.Models.Tag>("tags", Tags);
            writer.WriteStringValue("text", Text);
            writer.WriteCollectionOfPrimitiveValues<string>("to", To);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
