// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The type of automation step.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AutomationRunStepType
    {
        [EnumMember(Value = "trigger")]
        #pragma warning disable CS1591
        Trigger,
        #pragma warning restore CS1591
        [EnumMember(Value = "send_email")]
        #pragma warning disable CS1591
        SendEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "delay")]
        #pragma warning disable CS1591
        Delay,
        #pragma warning restore CS1591
        [EnumMember(Value = "wait_for_event")]
        #pragma warning disable CS1591
        WaitForEvent,
        #pragma warning restore CS1591
        [EnumMember(Value = "condition")]
        #pragma warning disable CS1591
        Condition,
        #pragma warning restore CS1591
        [EnumMember(Value = "contact_update")]
        #pragma warning disable CS1591
        ContactUpdate,
        #pragma warning restore CS1591
        [EnumMember(Value = "contact_delete")]
        #pragma warning disable CS1591
        ContactDelete,
        #pragma warning restore CS1591
        [EnumMember(Value = "add_to_segment")]
        #pragma warning disable CS1591
        AddToSegment,
        #pragma warning restore CS1591
    }
}
