// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The type of connection. Defaults to `default`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum AutomationConnectionType
    {
        [EnumMember(Value = "default")]
        #pragma warning disable CS1591
        DefaultValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "condition_met")]
        #pragma warning disable CS1591
        ConditionMet,
        #pragma warning restore CS1591
        [EnumMember(Value = "condition_not_met")]
        #pragma warning disable CS1591
        ConditionNotMet,
        #pragma warning restore CS1591
        [EnumMember(Value = "timeout")]
        #pragma warning disable CS1591
        Timeout,
        #pragma warning restore CS1591
        [EnumMember(Value = "event_received")]
        #pragma warning disable CS1591
        EventReceived,
        #pragma warning restore CS1591
    }
}
