// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BroadcastsRecipientsTypeParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "sent")]
        #pragma warning disable CS1591
        Sent,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "opened")]
        #pragma warning disable CS1591
        Opened,
        #pragma warning restore CS1591
        [EnumMember(Value = "clicked")]
        #pragma warning disable CS1591
        Clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "bounced")]
        #pragma warning disable CS1591
        Bounced,
        #pragma warning restore CS1591
        [EnumMember(Value = "complained")]
        #pragma warning disable CS1591
        Complained,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribed")]
        #pragma warning disable CS1591
        Unsubscribed,
        #pragma warning restore CS1591
        [EnumMember(Value = "suppressed")]
        #pragma warning disable CS1591
        Suppressed,
        #pragma warning restore CS1591
    }
}
