// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The status of the domain.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateDomainResponse_status
    {
        [EnumMember(Value = "pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "verified")]
        #pragma warning disable CS1591
        Verified,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "not_started")]
        #pragma warning disable CS1591
        Not_started,
        #pragma warning restore CS1591
        [EnumMember(Value = "partially_verified")]
        #pragma warning disable CS1591
        Partially_verified,
        #pragma warning restore CS1591
        [EnumMember(Value = "partially_failed")]
        #pragma warning disable CS1591
        Partially_failed,
        #pragma warning restore CS1591
    }
}
