// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreateDomainClaimRequest : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Track clicks within the body of each HTML email.</summary>
        public bool? ClickTracking { get; set; }
        /// <summary>For advanced use cases, choose a subdomain for the Return-Path address. Defaults to &apos;send&apos; (i.e., send.yourdomain.tld).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomReturnPath { get; set; }
#nullable restore
#else
        public string CustomReturnPath { get; set; }
#endif
        /// <summary>The name of the domain you want to claim.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Track the open rate of each email.</summary>
        public bool? OpenTracking { get; set; }
        /// <summary>The region where emails will be sent from. Possible values are us-east-1 | eu-west-1 | sa-east-1 | ap-northeast-1</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.CreateDomainClaimRequestRegion? Region { get; set; }
        /// <summary>The subdomain to use for click and open tracking.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TrackingSubdomain { get; set; }
#nullable restore
#else
        public string TrackingSubdomain { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.CreateDomainClaimRequest"/> and sets the default values.
        /// </summary>
        public CreateDomainClaimRequest()
        {
            AdditionalData = new Dictionary<string, object>();
            CustomReturnPath = "send";
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.CreateDomainClaimRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.CreateDomainClaimRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.CreateDomainClaimRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "click_tracking", n => { ClickTracking = n.GetBoolValue(); } },
                { "custom_return_path", n => { CustomReturnPath = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "open_tracking", n => { OpenTracking = n.GetBoolValue(); } },
                { "region", n => { Region = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.CreateDomainClaimRequestRegion>(); } },
                { "tracking_subdomain", n => { TrackingSubdomain = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("click_tracking", ClickTracking);
            writer.WriteStringValue("custom_return_path", CustomReturnPath);
            writer.WriteStringValue("name", Name);
            writer.WriteBoolValue("open_tracking", OpenTracking);
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.CreateDomainClaimRequestRegion>("region", Region);
            writer.WriteStringValue("tracking_subdomain", TrackingSubdomain);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
