// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The DNS record type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DomainRecord_type
    {
        [EnumMember(Value = "MX")]
        #pragma warning disable CS1591
        MX,
        #pragma warning restore CS1591
        [EnumMember(Value = "TXT")]
        #pragma warning disable CS1591
        TXT,
        #pragma warning restore CS1591
        [EnumMember(Value = "CNAME")]
        #pragma warning disable CS1591
        CNAME,
        #pragma warning restore CS1591
    }
}
