// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DomainClaim : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Why the claim is currently blocked, if applicable.</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.DomainClaimBlockedReason? BlockedReason { get; set; }
        /// <summary>The date and time the claim was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The ID of the placeholder domain created for the claim.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DomainId { get; set; }
#nullable restore
#else
        public string DomainId { get; set; }
#endif
        /// <summary>The date and time the claim expires if not verified.</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>Why the claim failed, if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FailureReason { get; set; }
#nullable restore
#else
        public string FailureReason { get; set; }
#endif
        /// <summary>The ID of the claim.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name of the domain being claimed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The type of object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Object { get; set; }
#nullable restore
#else
        public string Object { get; set; }
#endif
        /// <summary>The TXT record to add to your DNS to prove ownership of the claimed domain.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.DomainClaimRecord? Record { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.DomainClaimRecord Record { get; set; }
#endif
        /// <summary>The region where the claimed domain will send from.</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.DomainClaimRegion? Region { get; set; }
        /// <summary>The status of the claim.</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.DomainClaimStatus? Status { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.DomainClaim"/> and sets the default values.
        /// </summary>
        public DomainClaim()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.DomainClaim"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.DomainClaim CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.DomainClaim();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blocked_reason", n => { BlockedReason = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainClaimBlockedReason>(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "domain_id", n => { DomainId = n.GetStringValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "failure_reason", n => { FailureReason = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "object", n => { Object = n.GetStringValue(); } },
                { "record", n => { Record = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.DomainClaimRecord>(global::Soenneker.Resend.OpenApiClient.Models.DomainClaimRecord.CreateFromDiscriminatorValue); } },
                { "region", n => { Region = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainClaimRegion>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainClaimStatus>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainClaimBlockedReason>("blocked_reason", BlockedReason);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("domain_id", DomainId);
            writer.WriteDateTimeOffsetValue("expires_at", ExpiresAt);
            writer.WriteStringValue("failure_reason", FailureReason);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("object", Object);
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.DomainClaimRecord>("record", Record);
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainClaimRegion>("region", Region);
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainClaimStatus>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
