// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DomainRecord : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The name of the DNS record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The priority of the record (only applicable for MX records).</summary>
        public int? Priority { get; set; }
        /// <summary>The type of record (SPF for sending, DKIM for sending, Receiving for inbound emails).</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.DomainRecord_record? Record { get; set; }
        /// <summary>The status of the record.</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.DomainRecord_status? Status { get; set; }
        /// <summary>The time to live for the record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Ttl { get; set; }
#nullable restore
#else
        public string Ttl { get; set; }
#endif
        /// <summary>The DNS record type.</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.DomainRecord_type? Type { get; set; }
        /// <summary>The value of the record.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Value { get; set; }
#nullable restore
#else
        public string Value { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.DomainRecord"/> and sets the default values.
        /// </summary>
        public DomainRecord()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.DomainRecord"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.DomainRecord CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.DomainRecord();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "name", n => { Name = n.GetStringValue(); } },
                { "priority", n => { Priority = n.GetIntValue(); } },
                { "record", n => { Record = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainRecord_record>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainRecord_status>(); } },
                { "ttl", n => { Ttl = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainRecord_type>(); } },
                { "value", n => { Value = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("name", Name);
            writer.WriteIntValue("priority", Priority);
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainRecord_record>("record", Record);
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainRecord_status>("status", Status);
            writer.WriteStringValue("ttl", Ttl);
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.DomainRecord_type>("type", Type);
            writer.WriteStringValue("value", Value);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
