// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The DNS record type. Always TXT for domain claims.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum DomainClaimRecordType
    {
        [EnumMember(Value = "TXT")]
        #pragma warning disable CS1591
        Txt,
        #pragma warning restore CS1591
    }
}
