// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EmailsMetricsMetricsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "received")]
        #pragma warning disable CS1591
        Received,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivered")]
        #pragma warning disable CS1591
        Delivered,
        #pragma warning restore CS1591
        [EnumMember(Value = "complained")]
        #pragma warning disable CS1591
        Complained,
        #pragma warning restore CS1591
        [EnumMember(Value = "suppressed")]
        #pragma warning disable CS1591
        Suppressed,
        #pragma warning restore CS1591
        [EnumMember(Value = "bounced")]
        #pragma warning disable CS1591
        Bounced,
        #pragma warning restore CS1591
        [EnumMember(Value = "bounced_transient")]
        #pragma warning disable CS1591
        BouncedTransient,
        #pragma warning restore CS1591
        [EnumMember(Value = "bounced_permanent")]
        #pragma warning disable CS1591
        BouncedPermanent,
        #pragma warning restore CS1591
        [EnumMember(Value = "bounced_undetermined")]
        #pragma warning disable CS1591
        BouncedUndetermined,
        #pragma warning restore CS1591
        [EnumMember(Value = "opened")]
        #pragma warning disable CS1591
        Opened,
        #pragma warning restore CS1591
        [EnumMember(Value = "clicked")]
        #pragma warning disable CS1591
        Clicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribed")]
        #pragma warning disable CS1591
        Unsubscribed,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivery_delayed")]
        #pragma warning disable CS1591
        DeliveryDelayed,
        #pragma warning restore CS1591
        [EnumMember(Value = "failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "sent")]
        #pragma warning disable CS1591
        Sent,
        #pragma warning restore CS1591
        [EnumMember(Value = "unique_opened")]
        #pragma warning disable CS1591
        UniqueOpened,
        #pragma warning restore CS1591
        [EnumMember(Value = "unique_clicked")]
        #pragma warning disable CS1591
        UniqueClicked,
        #pragma warning restore CS1591
        [EnumMember(Value = "delivery_rate")]
        #pragma warning disable CS1591
        DeliveryRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "open_rate")]
        #pragma warning disable CS1591
        OpenRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "click_rate")]
        #pragma warning disable CS1591
        ClickRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "bounce_rate")]
        #pragma warning disable CS1591
        BounceRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "complaint_rate")]
        #pragma warning disable CS1591
        ComplaintRate,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribe_rate")]
        #pragma warning disable CS1591
        UnsubscribeRate,
        #pragma warning restore CS1591
    }
}
