// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum EmailsMetricsDimensionsParameterItem
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "period")]
        #pragma warning disable CS1591
        Period,
        #pragma warning restore CS1591
        [EnumMember(Value = "domain")]
        #pragma warning disable CS1591
        Domain,
        #pragma warning restore CS1591
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "broadcast")]
        #pragma warning disable CS1591
        Broadcast,
        #pragma warning restore CS1591
    }
}
