// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The subtype of the bounce, as reported by AWS SES.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EmailBounceSubType
    {
        [EnumMember(Value = "Undetermined")]
        #pragma warning disable CS1591
        Undetermined,
        #pragma warning restore CS1591
        [EnumMember(Value = "General")]
        #pragma warning disable CS1591
        General,
        #pragma warning restore CS1591
        [EnumMember(Value = "NoEmail")]
        #pragma warning disable CS1591
        NoEmail,
        #pragma warning restore CS1591
        [EnumMember(Value = "MailboxFull")]
        #pragma warning disable CS1591
        MailboxFull,
        #pragma warning restore CS1591
        [EnumMember(Value = "MessageTooLarge")]
        #pragma warning disable CS1591
        MessageTooLarge,
        #pragma warning restore CS1591
        [EnumMember(Value = "ContentRejected")]
        #pragma warning disable CS1591
        ContentRejected,
        #pragma warning restore CS1591
        [EnumMember(Value = "AttachmentRejected")]
        #pragma warning disable CS1591
        AttachmentRejected,
        #pragma warning restore CS1591
    }
}
