// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EmailSuppressedEventData : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Unique identifier for the broadcast campaign, if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BroadcastId { get; set; }
#nullable restore
#else
        public string BroadcastId { get; set; }
#endif
        /// <summary>Timestamp when the email was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Unique identifier for the email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EmailId { get; set; }
#nullable restore
#else
        public string EmailId { get; set; }
#endif
        /// <summary>Sender email address and name in the format `Name &lt;email@domain.com&gt;`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? From { get; set; }
#nullable restore
#else
        public string From { get; set; }
#endif
        /// <summary>Custom headers included with the email (omitted when no custom headers are set).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Resend.OpenApiClient.Models.OutboundEmailEventDataHeadersItem>? Headers { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Resend.OpenApiClient.Models.OutboundEmailEventDataHeadersItem> Headers { get; set; }
#endif
        /// <summary>Email subject line.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The suppressed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.WebhookEventSuppressed? Suppressed { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.WebhookEventSuppressed Suppressed { get; set; }
#endif
        /// <summary>Tag key-value pairs associated with the email.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.EmailSuppressedEventDataTags? Tags { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.EmailSuppressedEventDataTags Tags { get; set; }
#endif
        /// <summary>Unique identifier for the template used, if applicable.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TemplateId { get; set; }
#nullable restore
#else
        public string TemplateId { get; set; }
#endif
        /// <summary>Array of impacted recipient email addresses.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? To { get; set; }
#nullable restore
#else
        public List<string> To { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.EmailSuppressedEventData"/> and sets the default values.
        /// </summary>
        public EmailSuppressedEventData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.EmailSuppressedEventData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.EmailSuppressedEventData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.EmailSuppressedEventData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "broadcast_id", n => { BroadcastId = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "email_id", n => { EmailId = n.GetStringValue(); } },
                { "from", n => { From = n.GetStringValue(); } },
                { "headers", n => { Headers = n.GetCollectionOfObjectValues<global::Soenneker.Resend.OpenApiClient.Models.OutboundEmailEventDataHeadersItem>(global::Soenneker.Resend.OpenApiClient.Models.OutboundEmailEventDataHeadersItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "suppressed", n => { Suppressed = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.WebhookEventSuppressed>(global::Soenneker.Resend.OpenApiClient.Models.WebhookEventSuppressed.CreateFromDiscriminatorValue); } },
                { "tags", n => { Tags = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.EmailSuppressedEventDataTags>(global::Soenneker.Resend.OpenApiClient.Models.EmailSuppressedEventDataTags.CreateFromDiscriminatorValue); } },
                { "template_id", n => { TemplateId = n.GetStringValue(); } },
                { "to", n => { To = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("broadcast_id", BroadcastId);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("email_id", EmailId);
            writer.WriteStringValue("from", From);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Resend.OpenApiClient.Models.OutboundEmailEventDataHeadersItem>("headers", Headers);
            writer.WriteStringValue("subject", Subject);
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.WebhookEventSuppressed>("suppressed", Suppressed);
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.EmailSuppressedEventDataTags>("tags", Tags);
            writer.WriteStringValue("template_id", TemplateId);
            writer.WriteCollectionOfPrimitiveValues<string>("to", To);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
