// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>
    /// A single breakdown row. Which dimension fields are present depends on the requested `dimensions`; which metric fields are present depends on the requested `metrics`.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class EmailMetricsDataRow : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Present when `broadcast` is in `dimensions`.</summary>
        public Guid? BroadcastId { get; set; }
        /// <summary>Present when `broadcast` is in `dimensions`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BroadcastName { get; set; }
#nullable restore
#else
        public string BroadcastName { get; set; }
#endif
        /// <summary>Present when `domain` is in `dimensions`.</summary>
        public Guid? DomainId { get; set; }
        /// <summary>Present when `domain` is in `dimensions`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DomainName { get; set; }
#nullable restore
#else
        public string DomainName { get; set; }
#endif
        /// <summary>Present when `email` is in `dimensions`.</summary>
        public Guid? EmailId { get; set; }
        /// <summary>Present when `period` is in `dimensions`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Period { get; set; }
#nullable restore
#else
        public string Period { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.EmailMetricsDataRow"/> and sets the default values.
        /// </summary>
        public EmailMetricsDataRow()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.EmailMetricsDataRow"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.EmailMetricsDataRow CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.EmailMetricsDataRow();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "broadcast_id", n => { BroadcastId = n.GetGuidValue(); } },
                { "broadcast_name", n => { BroadcastName = n.GetStringValue(); } },
                { "domain_id", n => { DomainId = n.GetGuidValue(); } },
                { "domain_name", n => { DomainName = n.GetStringValue(); } },
                { "email_id", n => { EmailId = n.GetGuidValue(); } },
                { "period", n => { Period = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteGuidValue("broadcast_id", BroadcastId);
            writer.WriteStringValue("broadcast_name", BroadcastName);
            writer.WriteGuidValue("domain_id", DomainId);
            writer.WriteStringValue("domain_name", DomainName);
            writer.WriteGuidValue("email_id", EmailId);
            writer.WriteStringValue("period", Period);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
