// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The type of bounce, as reported by AWS SES.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum EmailBounceType
    {
        [EnumMember(Value = "Undetermined")]
        #pragma warning disable CS1591
        Undetermined,
        #pragma warning restore CS1591
        [EnumMember(Value = "Transient")]
        #pragma warning disable CS1591
        Transient,
        #pragma warning restore CS1591
        [EnumMember(Value = "Permanent")]
        #pragma warning disable CS1591
        Permanent,
        #pragma warning restore CS1591
    }
}
