// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The response object type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetBroadcastMetricsResponseSuccess_object
    {
        [EnumMember(Value = "broadcast_metrics")]
        #pragma warning disable CS1591
        BroadcastMetrics,
        #pragma warning restore CS1591
    }
}
