// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetBroadcastMetricsResponseSuccess : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The bounced property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter? Bounced { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter Bounced { get; set; }
#endif
        /// <summary>The broadcast_id property</summary>
        public Guid? BroadcastId { get; set; }
        /// <summary>The clicked property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter? Clicked { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter Clicked { get; set; }
#endif
        /// <summary>The complained property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter? Complained { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter Complained { get; set; }
#endif
        /// <summary>The delivered property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter? Delivered { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter Delivered { get; set; }
#endif
        /// <summary>The response object type.</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.GetBroadcastMetricsResponseSuccess_object? Object { get; set; }
        /// <summary>The opened property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter? Opened { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter Opened { get; set; }
#endif
        /// <summary>Emails sent so far (delivered + bounced while the broadcast is still sending).</summary>
        public int? Sent { get; set; }
        /// <summary>The suppressed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter? Suppressed { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter Suppressed { get; set; }
#endif
        /// <summary>Audience size the broadcast was sent to.</summary>
        public int? Total { get; set; }
        /// <summary>The unsubscribed property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter? Unsubscribed { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter Unsubscribed { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.GetBroadcastMetricsResponseSuccess"/> and sets the default values.
        /// </summary>
        public GetBroadcastMetricsResponseSuccess()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.GetBroadcastMetricsResponseSuccess"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.GetBroadcastMetricsResponseSuccess CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.GetBroadcastMetricsResponseSuccess();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bounced", n => { Bounced = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>(global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter.CreateFromDiscriminatorValue); } },
                { "broadcast_id", n => { BroadcastId = n.GetGuidValue(); } },
                { "clicked", n => { Clicked = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>(global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter.CreateFromDiscriminatorValue); } },
                { "complained", n => { Complained = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>(global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter.CreateFromDiscriminatorValue); } },
                { "delivered", n => { Delivered = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>(global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter.CreateFromDiscriminatorValue); } },
                { "object", n => { Object = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.GetBroadcastMetricsResponseSuccess_object>(); } },
                { "opened", n => { Opened = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>(global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter.CreateFromDiscriminatorValue); } },
                { "sent", n => { Sent = n.GetIntValue(); } },
                { "suppressed", n => { Suppressed = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>(global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter.CreateFromDiscriminatorValue); } },
                { "total", n => { Total = n.GetIntValue(); } },
                { "unsubscribed", n => { Unsubscribed = n.GetObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>(global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>("bounced", Bounced);
            writer.WriteGuidValue("broadcast_id", BroadcastId);
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>("clicked", Clicked);
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>("complained", Complained);
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>("delivered", Delivered);
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.GetBroadcastMetricsResponseSuccess_object>("object", Object);
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>("opened", Opened);
            writer.WriteIntValue("sent", Sent);
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>("suppressed", Suppressed);
            writer.WriteIntValue("total", Total);
            writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.BroadcastMetricCounter>("unsubscribed", Unsubscribed);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
