// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The bucket size used when `period` is in `dimensions`.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetEmailsMetricsResponseGranularity
    {
        [EnumMember(Value = "hourly")]
        #pragma warning disable CS1591
        Hourly,
        #pragma warning restore CS1591
        [EnumMember(Value = "daily")]
        #pragma warning disable CS1591
        Daily,
        #pragma warning restore CS1591
        [EnumMember(Value = "weekly")]
        #pragma warning disable CS1591
        Weekly,
        #pragma warning restore CS1591
        [EnumMember(Value = "monthly")]
        #pragma warning disable CS1591
        Monthly,
        #pragma warning restore CS1591
    }
}
