// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>Origin of the suppression.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum GetSuppressionResponseSuccessOrigin
    {
        [EnumMember(Value = "bounce")]
        #pragma warning disable CS1591
        Bounce,
        #pragma warning restore CS1591
        [EnumMember(Value = "complaint")]
        #pragma warning disable CS1591
        Complaint,
        #pragma warning restore CS1591
        [EnumMember(Value = "manual")]
        #pragma warning disable CS1591
        Manual,
        #pragma warning restore CS1591
    }
}
