// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetUsageResponseSuccessEmailsMonthly : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The monthly plan limit.</summary>
        public int? Limit { get; set; }
        /// <summary>Emails received this billing period.</summary>
        public int? Received { get; set; }
        /// <summary>When the monthly counter resets, as an ISO 8601 datetime.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResetsAt { get; set; }
#nullable restore
#else
        public string ResetsAt { get; set; }
#endif
        /// <summary>Emails sent this billing period.</summary>
        public int? Sent { get; set; }
        /// <summary>Emails sent and received in the current billing period.</summary>
        public int? Used { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.GetUsageResponseSuccessEmailsMonthly"/> and sets the default values.
        /// </summary>
        public GetUsageResponseSuccessEmailsMonthly()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.GetUsageResponseSuccessEmailsMonthly"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.GetUsageResponseSuccessEmailsMonthly CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.GetUsageResponseSuccessEmailsMonthly();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "limit", n => { Limit = n.GetIntValue(); } },
                { "received", n => { Received = n.GetIntValue(); } },
                { "resets_at", n => { ResetsAt = n.GetStringValue(); } },
                { "sent", n => { Sent = n.GetIntValue(); } },
                { "used", n => { Used = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("limit", Limit);
            writer.WriteIntValue("received", Received);
            writer.WriteStringValue("resets_at", ResetsAt);
            writer.WriteIntValue("sent", Sent);
            writer.WriteIntValue("used", Used);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
