// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The default subscription status for the topic.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListTopicsResponseSuccessDataItemDefaultSubscription
    {
        [EnumMember(Value = "opt_in")]
        #pragma warning disable CS1591
        OptIn,
        #pragma warning restore CS1591
        [EnumMember(Value = "opt_out")]
        #pragma warning disable CS1591
        OptOut,
        #pragma warning restore CS1591
    }
}
