// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ListBroadcastRecipientsResponseSuccessDataItem : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The type of bounce. Only present when `type` is `bounced`.</summary>
        public global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItemBounceType? BounceType { get; set; }
        /// <summary>The links this recipient clicked. Only present when `type` is `clicked`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItemClickedLinksItem>? ClickedLinks { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItemClickedLinksItem> ClickedLinks { get; set; }
#endif
        /// <summary>The ID of the contact associated with this recipient, if one exists.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContactId { get; set; }
#nullable restore
#else
        public string ContactId { get; set; }
#endif
        /// <summary>The number of times this recipient triggered the event. Only present when `type` is `opened` or `clicked`.</summary>
        public int? Count { get; set; }
        /// <summary>The recipient&apos;s email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Email { get; set; }
#nullable restore
#else
        public string Email { get; set; }
#endif
        /// <summary>Opaque cursor identifying this row, used for pagination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItem"/> and sets the default values.
        /// </summary>
        public ListBroadcastRecipientsResponseSuccessDataItem()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bounce_type", n => { BounceType = n.GetEnumValue<global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItemBounceType>(); } },
                { "clicked_links", n => { ClickedLinks = n.GetCollectionOfObjectValues<global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItemClickedLinksItem>(global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItemClickedLinksItem.CreateFromDiscriminatorValue)?.AsList(); } },
                { "contact_id", n => { ContactId = n.GetStringValue(); } },
                { "count", n => { Count = n.GetIntValue(); } },
                { "email", n => { Email = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItemBounceType>("bounce_type", BounceType);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Resend.OpenApiClient.Models.ListBroadcastRecipientsResponseSuccessDataItemClickedLinksItem>("clicked_links", ClickedLinks);
            writer.WriteStringValue("contact_id", ContactId);
            writer.WriteIntValue("count", Count);
            writer.WriteStringValue("email", Email);
            writer.WriteStringValue("id", Id);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
