// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>How the attachment should be displayed.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ListReceivedEmailsResponse_data_attachments_content_disposition
    {
        [EnumMember(Value = "inline")]
        #pragma warning disable CS1591
        Inline,
        #pragma warning restore CS1591
        [EnumMember(Value = "attachment")]
        #pragma warning disable CS1591
        Attachment,
        #pragma warning restore CS1591
    }
}
