// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The publication status of the template.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Template_status
    {
        [EnumMember(Value = "draft")]
        #pragma warning disable CS1591
        Draft,
        #pragma warning restore CS1591
        [EnumMember(Value = "published")]
        #pragma warning disable CS1591
        Published,
        #pragma warning restore CS1591
    }
}
