// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch1"/>, <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch2"/>, <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch3"/>, <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch5"/>, <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueMember1"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TemplateVariableFallbackValue : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch1? TemplateVariableFallbackValueBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch1 TemplateVariableFallbackValueBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch2"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch2? TemplateVariableFallbackValueBranch2 { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch2 TemplateVariableFallbackValueBranch2 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch3"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch3? TemplateVariableFallbackValueBranch3 { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch3 TemplateVariableFallbackValueBranch3 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch5"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch5? TemplateVariableFallbackValueBranch5 { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch5 TemplateVariableFallbackValueBranch5 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueMember1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueMember1? TemplateVariableFallbackValueMember1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueMember1 TemplateVariableFallbackValueMember1 { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValue();
            if("TemplateVariableFallbackValue_1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TemplateVariableFallbackValueBranch1 = new global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch1();
            }
            else if("TemplateVariableFallbackValue_2".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TemplateVariableFallbackValueBranch2 = new global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch2();
            }
            else if("TemplateVariableFallbackValue_3".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TemplateVariableFallbackValueBranch3 = new global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch3();
            }
            else if("TemplateVariableFallbackValue_5".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.TemplateVariableFallbackValueBranch5 = new global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch5();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(TemplateVariableFallbackValueBranch1 != null)
            {
                return TemplateVariableFallbackValueBranch1.GetFieldDeserializers();
            }
            else if(TemplateVariableFallbackValueBranch2 != null)
            {
                return TemplateVariableFallbackValueBranch2.GetFieldDeserializers();
            }
            else if(TemplateVariableFallbackValueBranch3 != null)
            {
                return TemplateVariableFallbackValueBranch3.GetFieldDeserializers();
            }
            else if(TemplateVariableFallbackValueBranch5 != null)
            {
                return TemplateVariableFallbackValueBranch5.GetFieldDeserializers();
            }
            else if(TemplateVariableFallbackValueMember1 != null)
            {
                return TemplateVariableFallbackValueMember1.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(TemplateVariableFallbackValueBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch1>(null, TemplateVariableFallbackValueBranch1);
            }
            else if(TemplateVariableFallbackValueBranch2 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch2>(null, TemplateVariableFallbackValueBranch2);
            }
            else if(TemplateVariableFallbackValueBranch3 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch3>(null, TemplateVariableFallbackValueBranch3);
            }
            else if(TemplateVariableFallbackValueBranch5 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueBranch5>(null, TemplateVariableFallbackValueBranch5);
            }
            else if(TemplateVariableFallbackValueMember1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Resend.OpenApiClient.Models.TemplateVariableFallbackValueMember1>(null, TemplateVariableFallbackValueMember1);
            }
        }
    }
}
#pragma warning restore CS0618
