// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Resend.OpenApiClient.Models
{
    /// <summary>The event type.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TopicDeletedType
    {
        [EnumMember(Value = "topic.deleted")]
        #pragma warning disable CS1591
        TopicDeleted,
        #pragma warning restore CS1591
    }
}
